CREATE TABLE PUBLIC.PRICES
(
    ID            INT                       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID      INT REFERENCES BRANDS     NOT NULL,
    START_DATE    TIMESTAMP WITH TIME ZONE  NOT NULL,
    END_DATE      TIMESTAMP WITH TIME ZONE  NOT NULL,
    PRICE_LIST_ID INT REFERENCES PRICE_LIST NOT NULL,
    PRODUCT_ID    INT REFERENCES PRODUCTS   NOT NULL,
    PRIORITY_ID   INT REFERENCES PRIORITIES NOT NULL,
    COST          DECIMAL(10, 2)            NOT NULL,
    CURRENT_ID    INT REFERENCES CURRENCIES NOT NULL
--     CONSTRAINT brand_product_priority_pkey
--         UNIQUE (BRAND_ID, START_DATE, END_DATE, PRODUCT_ID, PRIORITY_ID)
);
